name: PGCL
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libmpdec=4.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.13.9
  - python_abi=3.13
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - gpytoolbox==0.3.7
      - imageio==2.37.2
      - lazy-loader==0.4
      - networkx==3.5
      - numpy==2.2.6
      - packaging==25.0
      - pillow==12.0.0
      - polyscope==2.2.1
      - scikit-image==0.25.2
      - scipy==1.15.0
      - scs==3.2.9
      - tifffile==2025.10.16
prefix: /home/dany/miniconda3/envs/PGCL
